### ISSUE TITLE
[sortStrictlyByVotes.user.js] When going to a link to a specific answer, the browser doesn't focus on the linked answer with the script enabled

### ISSUE THREAD

**Issue by AmperAndSand** [shu8/SE-Answers_scripts#1]
When I go to a link to a specific answer, e.g. http://superuser.com/a/260658/ - the browser focuses on the 'Post your answer' form:
![screenshot](https://cloud.githubusercontent.com/assets/1404745/9625434/a17803ea-5188-11e5-96a7-f57919f75155.png)
The default behavior without this script is to focus on the answer linked to:
![screenshot](https://cloud.githubusercontent.com/assets/1404745/9625444/bcf4c888-5188-11e5-913a-d04fbb8dde68.png)

---

This happens on every question I've tested on Super User and Arqade. I'm using v1.1 of the script on Greasemonkey and Firefox 40.0.3.

**Comment by shu8** [comment]
Weird, but I will look into it ASAP! :) Thanks for the test case and everything :P

**Comment by shu8** [comment]
@AmperAndSand fixed in 1.2 :)

It's a bit hacky, but I hope it will do! :/
