### ISSUE TITLE
willQuestionBeDeleted.user.js seems to have stopped working for negatively scored questions with at least one answer, but none is accepted or positively scored

### ISSUE THREAD

**Issue by AmperAndSand** [shu8/SE-Answers_scripts#10]
[willQuestionBeDeleted.user.js](https://github.com/shu8/SE-Answers_scripts/blob/master/willQuestionBeDeleted.user.js) seems to have stopped working recently. Here is a recently closed "needs details or clarity" question that currently has -1 votes and has one non-accepted answer with -1 votes, but the script does not show any message on it: https://gaming.stackexchange.com/questions/275899/minecraft-download-problem

The question is a candidate for deletion as per the Meta SE post: [How does deleting work? What can cause a post to be deleted, and what does that actually mean? What are the criteria for deletion?](https://meta.stackexchange.com/q/5221/)

>The system will automatically delete closed, unlocked, and non-migrated questions that have zero or negative score, have no positively scored or accepted answers or pending reopen votes, were closed for any reason other than duplicate nine or more days ago, and haven't been edited in the past nine days. […]

**Comment by shu8** [comment]
Thanks for the bug report! The script was previously only checking for "0 answers" -- I've now tweaked it so it checks for "0 positively scoring answers" -- hopefully this should be resolved now!
