### ISSUE TITLE
Update for isolated editors

### ISSUE THREAD

**Issue by szego** [shu8/SE-Answers_scripts#3]
Hey Shub,

I've been working on the sbs script a bit more since I noticed it didn't work for a few different editors on the site, namely:
- the editor that is created when you click the "Answer your own question" checkbox on the /questions/ask/ page
- editors in the review queue
- if your rep on a site is so low that your edits are "suggested edits" (which need to be reviewed), instead of getting an inline editor when you click the "edit" link on a question/answer you get taken to a separate page with an isolated editor

The new code is in a dev branch:

https://github.com/szego/SE-Answers_scripts/blob/side-by-side-dev/side-by-side-editing.user.js

I've been using this version for a while without noticing anything strange, so I think it should be stable. Would it be alright to send a pull request for this to be version 1.2 of the script?

Cheers,

Tony

**Comment by shu8** [comment]
Sure! No problem - I'd greatly appreciate it.

However, I am away till the New Year and will be very busy for a few weeks,
so it may have to wait till mid-Jan or possibly later! :/

But feel free to submit pull requests, and if I get any time, I'll
review+accept them :)

Thanks again!

**Comment by szego** [comment]
Will do, have a good new year's!

**Comment by shu8** [comment]
@szego I'm finally free from all my work in the past few weeks, so if you can submit a pull request, I'll happily accept it! :)

BTW I'm not sure whether I told you that I had put this (the previous version) in my SOOF userscript (https://github.com/shu8/Stack-Overflow-Optional-Features) as well! :)
