### ISSUE TITLE
no longer working, probably due to update

### ISSUE THREAD

**Issue by polyluxus** [shu8/SE-Answers_scripts#5]
As of a few days ago (I think), the script stopped working, and now instead stretches the input window across the whole page, while the preview is still below:

![capture](https://user-images.githubusercontent.com/19774680/36582710-e211cbc4-18b5-11e8-85e6-403003c4c75d.PNG)

The above is an example from chemistry.se, but I found it not working on other sites, too.  
(I don't know anything about how these things work, so I can't suggest a fix, but I have become so dependent on this script.)

**Comment by shu8** [comment]
@polyluxus thanks for the bug report. I have another userscript called SOX (https://stackapps.com/questions/6091/stack-overflow-extras-sox) which contains this feature and lots more -- I've just fixed the feature on the DEV version of that script, so you can install that to get this and loads more! (they're all optional).

you can install the DEV version from here: https://github.com/soscripted/sox/raw/dev/sox.user.js
