### ISSUE TITLE
Script for side-by-side editing is no longer working on Stack Exchange sites

### ISSUE THREAD

**Issue by Quantum-Operator** [shu8/SE-Answers_scripts#6]
Hi, there was a time when the side by side editing worked brilliantly, but now the editing box just takes up the whole screen preventing you from seeing the output as you type. [This is what it looks like now](http://prntscr.com/kcadak).

It's a shame as this was a really useful script - written by username: szego (I think).

Is there a reason why this is not working? Or is there an updated version I couldn't find?

Many thanks.

Q

**Comment by shu8** [comment]
@Quantum-Operator I've now included this feature in my [SOX](https://stackapps.com/q/6091) userscript, which also adds a bunch of other optional features that you can toggle on/off depending on how you like them :)

Please do give it a try and it should work for you as we've updated that feature regularly as SE change the layout often!
