### ISSUE TITLE
Accepted answer with not max votes is at the top

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [shu8/SE-Answers_scripts#7]
I've installed the userscript Sort by votes, properly...v1.2 from the answer https://softwarerecs.stackexchange.com/questions/18392/firefox-extension-userscript-to-prevent-accepted-answer-from-sticking-to-top-on/18454#18454 
and opened https://stackoverflow.com/questions/15880574/json-net-how-to-deserialize-collection-of-interface-instances.
Both tabs "Votes" and "Real Votes" show accepted answer with 34 votes first, and answer with 79 votes second.
I expect to see answer with 79 votes first.

**Comment by shu8** [comment]
@michael-freidgeim-webjet thanks for letting me know!

I've [fixed that now](https://github.com/shu8/SE-Answers_scripts/raw/master/sortStrictlyByVotes.user.js) :)

However, I'd love it if you gave my other [userscript, SOX](https://stackapps.com/questions/6091/stack-overflow-extras-sox) a go -- it's a much bigger one that adds a bunch of other toggleable (you can enable/disable whichever ones you like!) features for all the Stack Exchange sites.

There is a feature in SOX called "Improve answer visibility by listing top answers" which intends to have the same effect as this one in a more graphical way, see this screenshot for what it would look like on the question you linked:

![image](https://user-images.githubusercontent.com/8850830/51630946-43117c00-1f43-11e9-9ba3-b9e62efc5844.png)

If not, I hope the fix I made to this one works for you! :)
