### ISSUE TITLE
willQuestionBeDeleted.user.js doesn't seem to work anymore

### ISSUE THREAD

**Issue by AmperAndSand** [shu8/SE-Answers_scripts#8]
I don't think I've seen [willQuestionBeDeleted.user.js](https://github.com/shu8/SE-Answers_scripts/blob/master/willQuestionBeDeleted.user.js) work for a year or two now. E.g., here is a question that is currently a candidate for deletion, but the script does not show any message on it: https://gaming.stackexchange.com/questions/376552/looking-for-old-car-game-racing 

As per Meta SE post, [How does deleting work? What can cause a post to be deleted, and what does that actually mean? What are the criteria for deletion?](https://meta.stackexchange.com/q/5221/):

>The system will automatically delete closed, unlocked, and non-migrated questions that have zero or negative score, have no positively scored or accepted answers or pending reopen votes, were closed for any reason other than duplicate...

>The system will automatically delete negatively-scored, non-migrated, unlocked, and unanswered questions (both open and closed, including as duplicates)...

**Comment by shu8** [comment]
@AmperAndSand I'm really sorry for the extremely delayed response and thank you for letting me know!

If you're still interested, hopefully [this should be fixed now](https://github.com/shu8/SE-Answers_scripts/blob/master/willQuestionBeDeleted.user.js)! :)
