### ISSUE TITLE
sortStrictlyByVotes.user.js currently doesn't work

### ISSUE THREAD

**Issue by AmperAndSand** [shu8/SE-Answers_scripts#9]
It seems that sortStrictlyByVotes.user.js currently doesn't work on sites that are [pinning the accepted answer to the top of the list of answers](https://meta.stackexchange.com/q/369568/162827).  The accepted answer will still be pinned at the top even if you sort by highest score.

E.g., at Web Apps SE (which has kept the pin on accepted answers): https://webapps.stackexchange.com/questions/99113/7584/google-sheets-execute-script-only-in-certain-range-on-certain-sheet

Tested on the Brave browser and Tampermonkey.

**Comment by shu8** [comment]
Thanks @AmperAndSand, this should now be fixed!
